server:
  port: 8099

spring:
  application:
    name: user-service

# eureka server url
#eureka.client.service-url.default-zone=http://localhost:8761/eureka

#Data
spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user
spring.datasource.username: springuser
spring.datasource.password: ThePassword
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl: true
